
import os
import pprint

WEAVIATE_URL = os.environ["WEAVIATE_URL"]
WEAVIATE_API_KEY = os.environ["WEAVIATE_API_KEY"]


def check_weaviate_schema_exist(client, class_name):
    try:
        class_schema = client.schema.get_class(class_name)
        print(f"Schema for class '{class_name}' exists:")
        print(class_schema)
        return True
    except Exception as e:
        print(f"Class '{class_name}' does not exist in the schema.")
        return False

def print_weaviate_schema(client):
    schema = client.schema.get()
    pprint.pprint(schema)

def determine_data_type(value):
    if isinstance(value, list):
        return "text[]"
    elif isinstance(value, int):
        return "int"
    elif isinstance(value, float):
        return "number"
    elif value is None:
        return "text"
    else:
        return "text"

def create_weaviate_schema(client, class_name, key, elements, tokenization_overrides, logger=None):
    try:
        schema = client.schema.get()
        existing_class = next((cls for cls in schema['classes'] if cls['class'] == class_name), None)

        if existing_class:
            existing_properties = {prop['name']: prop for prop in existing_class['properties']}
        else:
            existing_properties = {}

        other_keys = {k: determine_data_type(v) for k, v in elements[0].metadata.items()}

        # Define properties based on the input keys and tokenization_overrides
        properties = []
        key_name_list = []
        for key, data_type in other_keys.items():
            if key in tokenization_overrides:
                override = tokenization_overrides[key]
                if isinstance(override, tuple):
                    data_type, tokenization = override
                    if data_type == None or tokenization == None:
                        continue
                else:
                    tokenization = override
                    data_type = data_type
            else:
                tokenization = "word" if data_type in ["text", "text[]"] else None

            properties.append({
                "name": key,
                "dataType": ["text"] if data_type is None else [data_type],
                "description": f"This property was generated by Weaviate's auto-schema feature",
                "indexFilterable": True,
                "indexSearchable": data_type in ["text", "text[]"],
                "tokenization": tokenization
            })
            key_name_list.append(key)

        if existing_class:
            # Remove properties not present in the new schema
            schema_keys = [prop for prop in properties if prop['name'] in other_keys]
            schema_key_name_list = []
            not_schema_key_name_list = []
            for schema_key in schema_keys:
                if schema_key.get('name') in key_name_list:
                    schema_key_name_list.append(schema_key.get('name'))
                else:
                    not_schema_key_name_list.append(schema_key.get('name'))
            
            if not_schema_key_name_list:
                logger.error(f"in'create_weaviate_schema, the following keys found in elements' metadata are not found in the schema for class {class_name}: {not_schema_key_name_list}")

            return schema_key_name_list
        else:
            # Define the schema with optimized settings for best search performance
            class_obj = {
                "class": class_name,
                "description": "Documents for optimized search performance",
                "properties": properties,
                "invertedIndexConfig": {
                    "bm25": {"b": 0.75, "k1": 2.0},  # Adjusted for better term frequency impact
                    "cleanupIntervalSeconds": 60,
                    "stopwords": {"additions": None, "preset": "en", "removals": None}
                },
                "multiTenancyConfig": {"enabled": False},
                "replicationConfig": {"factor": 1},
                "shardingConfig": {
                    "actualCount": 1,
                    "actualVirtualCount": 128,
                    "desiredCount": 1,
                    "desiredVirtualCount": 128,
                    "function": "murmur3",
                    "key": "_id",
                    "strategy": "hash",
                    "virtualPerPhysical": 128
                },
                "vectorIndexConfig": {
                    "bq": {"enabled": False},
                    "cleanupIntervalSeconds": 300,
                    "distance": "cosine",
                    "dynamicEfFactor": 10,
                    "dynamicEfMax": 1000,
                    "dynamicEfMin": 500,
                    "ef": 1000,
                    "efConstruction": 200,
                    "flatSearchCutoff": 0,# Disable switching to flat search for exhaustive search
                    "maxConnections": 128,
                    "pq": {
                        "bitCompression": False,
                        "centroids": 256,
                        "enabled": False,
                        "encoder": {"distribution": "log-normal", "type": "kmeans"},
                        "segments": 0,
                        "trainingLimit": 100000
                    },
                    "skip": False,
                    "vectorCacheMaxObjects": 1000000000000
                },
                "vectorIndexType": "hnsw",
                "vectorizer": "none"  # external vectorizer
            }

            # Create the class in Weaviate
            client.schema.create_class(class_obj)
            logger.info(f"Weaviate schema created for class name: {class_name}.")
            return key_name_list
    except Exception as e:
        logger.error(f"An error occurred in create_weaviate_schema: {e}")



# # Create the client
# client = weaviate.Client(
#     url=WEAVIATE_URL,
#     auth_client_secret=AuthApiKey(api_key=WEAVIATE_API_KEY),
# )

# text_key = 'page_content'
# embedder_model = 'embedder_model'

# # Tokenization overrides with tuples (key, datatype, tokenization)
# tokenization_overrides = {
#     "filename": ("text", "field"),
#     "document_title": ("text", "field"),
#     "key_terms": ("text[]", "word"),
# }

# INDEX_NAME= 'Test_schema'

# elements = [
#     {
#         "page_content": "page content text",
#         "metadata": {
#             "filename": "document1.pdf",
#             "document_title": "Test Document",
#             "key_terms": ["term1", "term2", "term3"],
#             "page_count": 5,
#             "size": 1024.56,
#             "author": "John Doe",
#             "creation_date": "2024-06-25",
#             "is_active": True,
#             "version": None
#         }
#     },
#     {
#         "page_content": "page content text",
#         "metadata": {
#             "filename": "document2.docx",
#             "document_title": "Another Test Document",
#             "key_terms": ["keyword1", "keyword2"],
#             "page_count": 10,
#             "size": 2048.75,
#             "author": "Jane Smith",
#             "creation_date": "2024-06-24",
#             "is_active": False,
#             "version": "v1.0"
#         }
#     }
# ]

# create_weaviate_schema(
#     client, 
#     INDEX_NAME, 
#     text_key, 
#     elements,
#     tokenization_overrides
# )
